version: '3'

volumes:
  airflow-data:
    external: false
  marquez-data:
    external: false

services:

  airflow-db:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow-data:/var/lib/postgresql
    
  airflow:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - POSTGRES_HOST=airflow-db
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./docker/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - airflow-db
    command: ["wait-for-it.sh", "airflow-db:5432", "--", "/entrypoint.sh", "webserver"]

  marquez-db:
    image: 'postgres:9.6'
    ports:
      - '25432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=buendia
      - MARQUEZ_PASSWORD=macondo
    volumes:
      - marquez-data:/var/lib/postgresql
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  marquez-api:
    image: 'marquezproject/marquez:latest'
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - MARQUEZ_CONFIG=/usr/src/app/config.yml
      - POSTGRES_HOST=marquez-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
      - POSTGRES_USER=buendia
      - POSTGRES_PASSWORD=macondo
    volumes:
      - ./marquez-config.yml:/usr/src/app/config.yml
    depends_on:
      - marquez-db


