version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_python


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user coverage
      - run: pip install --user  -r requirements.txt
      - run: python -m flake8

  test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user  -r test-requirements.txt
      - run: python -m pytest ./test --cov=marquez_client --cov-report xml ./test
      - run: python -m codecov

  release:
    <<: *defaults
    working_directory: ~/marquez_python
    steps:
      - checkout
      - run: pip install --user twine
      - run: python setup.py sdist
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_python:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
