version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_python


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user  -r requirements.txt

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: pip install --user  -r test-requirements.txt
      - run:
          command: python -m pytest ./test

workflows:
  version: 2
  marquez_python:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
