version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_airflow


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install airflow from package
          environment:
            SLUGIFY_USES_TEXT_UNIDECODE: 'yes'
          command: pip install --user -e .
      - run: pip install --user flake8
      - run: python -m flake8

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install test dependencies
          environment:
            SLUGIFY_USES_TEXT_UNIDECODE: 'yes'
          command: pip install --user -r test-requirements.txt
      - run:
          name: Install marquez-airflow package
          command: pip install --user -e .
      - run:
          name:
          environment:
            AIRFLOW__CORE__DAGS_FOLDER: './tests/test_dags'
          command: python -m pytest --log-cli-level=INFO --ignore=tests/integration --cov=marquez --cov-report xml ./tests

  integration:
    machine: true
    environment:
      - COMPOSE_FILE: 'tests/integration/docker-compose.yml'
    steps:
      - checkout
      - run:
          name: Test
          command: tests/integration/run.sh

  release:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/release_check.sh
      - run: pip install --user twine
      - run: python setup.py sdist
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_airflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - test
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
