version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/marquez_python


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pip install -r requirements.txt

  test:
    <<: *defaults
    steps:
      - checkout
      - run: ./pytest ./test

workflows:
  version: 2
  marquez:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
