version: 2

jobs:
  test:
    docker:
      - image: circleci/node:11.9.0
    working_directory: ~/marquez-web
    environment:
      TZ: 'America/New_York'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ .Revision }}
            - v1-deps-{{ .Branch }}
      - run: npm install
      - run: npm run test
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ .Branch }}-{{ .Revision }}

  release:
    machine: true
    working_directory: ~/marquez-web
    steps:
      - checkout
      - run: .circleci/get-docker.sh
      - run: ./docker/login.sh
      - run: ./docker/build-and-push.sh $CIRCLE_TAG

workflows:
  version: 2
  marquez_web:
    jobs:
      - test
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              ignore: /.*/
